/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef PRESAGEEDK_AUTODEFS_H
#define PRESAGEEDK_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_PRESAGEEDK_NAME "PresageEDK"
#define S3E_EXT_PRESAGEEDK_HASH 0x8ddf55c0

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("PresageEDK", 7)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !PRESAGEEDK_AUTODEFS_H */
