/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "PresageEDK.h"


// Define S3E_EXT_SKIP_LOADER_CALL_LOCK on the user-side to skip LoaderCallStart/LoaderCallDone()-entry.
// e.g. in s3eNUI this is used for generic user-side IwUI-based implementation.
#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
#if (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)) || defined I3D_ARCH_NACLX86_64
// For platforms missing stack-switching (WP8, NaCl, etc.) make loader-entry via LoaderCallStart/LoaderCallDone() on the user-side.
#define LOADER_CALL_LOCK
#endif
#endif


#include "PresageEDK_interface.h"

static PresageEDKFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x8ddf55c0, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: PresageEDK");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x8ddf55c0, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool PresageEDKAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult PresageEDKRegister(PresageEDKCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(PRESAGEEDK_VERBOSE, ("calling PresageEDK[0] func: PresageEDKRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_PresageEDKRegister);
#endif

    s3eResult ret = g_Ext.m_PresageEDKRegister(cbid, fn, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_PresageEDKRegister);
#endif

    return ret;
}

s3eResult PresageEDKUnRegister(PresageEDKCallback cbid, s3eCallback fn)
{
    IwTrace(PRESAGEEDK_VERBOSE, ("calling PresageEDK[1] func: PresageEDKUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_PresageEDKUnRegister);
#endif

    s3eResult ret = g_Ext.m_PresageEDKUnRegister(cbid, fn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_PresageEDKUnRegister);
#endif

    return ret;
}

void PresageStart()
{
    IwTrace(PRESAGEEDK_VERBOSE, ("calling PresageEDK[2] func: PresageStart"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_PresageStart);
#endif

    g_Ext.m_PresageStart();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_PresageStart);
#endif

    return;
}

void PresageAdToServe()
{
    IwTrace(PRESAGEEDK_VERBOSE, ("calling PresageEDK[3] func: PresageAdToServe"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_PresageAdToServe);
#endif

    g_Ext.m_PresageAdToServe();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_PresageAdToServe);
#endif

    return;
}

void PresageLoadAd()
{
    IwTrace(PRESAGEEDK_VERBOSE, ("calling PresageEDK[4] func: PresageLoadAd"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_PresageLoadAd);
#endif

    g_Ext.m_PresageLoadAd();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_PresageLoadAd);
#endif

    return;
}

void PresageShowAd()
{
    IwTrace(PRESAGEEDK_VERBOSE, ("calling PresageEDK[5] func: PresageShowAd"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_PresageShowAd);
#endif

    g_Ext.m_PresageShowAd();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_PresageShowAd);
#endif

    return;
}

void PresageLaunchEula()
{
    IwTrace(PRESAGEEDK_VERBOSE, ("calling PresageEDK[6] func: PresageLaunchEula"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_PresageLaunchEula);
#endif

    g_Ext.m_PresageLaunchEula();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_PresageLaunchEula);
#endif

    return;
}
