/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*PresageEDKRegister_t)(PresageEDKCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*PresageEDKUnRegister_t)(PresageEDKCallback cbid, s3eCallback fn);
typedef       void(*PresageStart_t)();
typedef       void(*PresageAdToServe_t)();
typedef       void(*PresageLoadAd_t)();
typedef       void(*PresageShowAd_t)();
typedef       void(*PresageLaunchEula_t)();

/**
 * struct that gets filled in by PresageEDKRegister
 */
typedef struct PresageEDKFuncs
{
    PresageEDKRegister_t m_PresageEDKRegister;
    PresageEDKUnRegister_t m_PresageEDKUnRegister;
    PresageStart_t m_PresageStart;
    PresageAdToServe_t m_PresageAdToServe;
    PresageLoadAd_t m_PresageLoadAd;
    PresageShowAd_t m_PresageShowAd;
    PresageLaunchEula_t m_PresageLaunchEula;
} PresageEDKFuncs;
