/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_PRESAGEEDK_H
#define S3E_EXT_PRESAGEEDK_H

#include <s3eTypes.h>

typedef enum PresageEDKCallback
{
	PRESAGE_RESULT_OK=0,
	PRESAGE_RESULT_NO_AD=1,
	PRESAGE_RESULT_CANCELLED=2,
	PRESAGE_RESULT_ERROR=3,
	PRESAGE_RESULT_DISPLAYED=4,
	PRESAGE_EULA_OK=5,
	PRESAGE_NO_EULA=6,
	PRESAGE_EULA_CANCELLED=7,

	PRESAGEEDK_CALLBACK_MAX

} PresageAdResult;
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Report if the PresageEDK extension is available.
 * @return S3E_TRUE if the PresageEDK extension is available. S3E_FALSE otherwise.
 */
s3eBool PresageEDKAvailable();

/**
 * Registers a callback to be called for an operating system event.
 *
 * The available callback types are listed in @ref PresageEDKCallback.
 * @param cbid ID of the event for which to register.
 * @param fn callback function.
 * @param userData Value to pass to the @e userData parameter of @e NotifyFunc.
 * @return
 *  - @ref S3E_RESULT_SUCCESS if no error occurred.
 *  - @ref S3E_RESULT_ERROR if the operation failed.\n
 *
 * @see PresageEDKUnRegister
 * @note For more information on the system data passed as a parameter to the callback
 * registered using this function, see the @ref PresageEDKCallback enum.
 * @note It is not necessary to define a return value for any registered callback.
 */
s3eResult PresageEDKRegister(PresageEDKCallback cbid, s3eCallback fn, void* userData);

/**
 * Unregister a callback for a given event.
 * @param cbid ID of the callback to unregister.
 * @param fn Callback Function.
 * @return
 * - @ref S3E_RESULT_SUCCESS if no error occurred.
 * - @ref S3E_RESULT_ERROR if the operation failed.\n
 * @see PresageEDKRegister
 */
s3eResult PresageEDKUnRegister(PresageEDKCallback cbid, s3eCallback fn);

void PresageStart();

void PresageAdToServe();

void PresageLoadAd();

void PresageShowAd();

void PresageLaunchEula();

// \cond HIDDEN_DEFINES
S3E_END_C_DECL
// \endcond


#endif /* !S3E_EXT_PRESAGEEDK_H */
